### ISSUE TITLE
Modyfying boardctrl_startup() appears to breaks things

### ISSUE THREAD

**Issue by mdaeron** [glenn20/upy-esp32-experiments#2]
I'm building firmware for a Lolin S2 Mini board using the following script:

```sh
#!/bin/zsh

DIR=`pwd`
BOARD=LOLIN_S2_MINI

# COMMENT NEXT FOUR LINES IF ESP-IDF IS ALREADY INSTALLED
git clone --depth 1 -b v5.0.2 --recursive https://github.com/espressif/esp-idf.git
cd $DIR/esp-idf
git submodule update --init --recursive
./install.sh

cd $DIR/esp-idf
source export.sh

git clone https://github.com/micropython/micropython.git --depth 1 --branch master --single-branch $DIR/micropython

# THE NEXT THREE LINES ARE FOR MINIMIZING STARTUP TIME (CF https://github.com/glenn20/upy-esp32-experiments)
# cat $DIR/main.py >> $DIR/micropython/ports/esp32/modules/_boot.py
# echo "\nCONFIG_BOOTLOADER_SKIP_VALIDATE_IN_DEEP_SLEEP=y" >> $DIR/micropython/ports/esp32/boards/sdkconfig.base
# gsed -i "/void boardctrl_startup(void) {/a\    if (esp_reset_reason() == ESP_RST_DEEPSLEEP) {\n        return;\n    }" $DIR/micropython/ports/esp32/main.c

cd $DIR/micropython
make -C mpy-cross

cd $DIR/micropython/ports/esp32
make submodules BOARD=$BOARD
make BOARD=$BOARD
make erase BOARD=$BOARD PORT=`ls /dev/tty.usb*`
make deploy BOARD=$BOARD PORT=`ls /dev/tty.usb*`
```

The code in `main.py` uses ESPNow to send a message and deep sleeps for 10s:

```py
SLEEP = 10 # seconds
PEER = b'\xaa\xaa\xaa\xaa\xaa\xaa' # arbitrary address for posting an issue
CHANNEL = 6

import network
from machine import deepsleep, reset_cause, DEEPSLEEP_RESET
from time import sleep_ms
from espnow import ESPNow

if not reset_cause() == DEEPSLEEP_RESET:
	sleep_ms(3000)

sta_if = network.WLAN(network.STA_IF)
sta_if.active(False)

ap_if = network.WLAN(network.AP_IF)
ap_if.active(True)
ap_if.config(hidden = True)
ap_if.config(channel = CHANNEL)

e = ESPNow()
e.active(True)
e.add_peer(PEER, ifidx = network.AP_IF, channel = CHANNEL)

e.send(PEER, 'loc=foo,T=25.0,RH=50.0')

deepsleep(1000 * SLEEP)
```

* When I run the build script as is and copy `main.py` to flash memory, everything works: I get the expected message every 10s.
* It still works the same if I uncomment only the first line (`cat $DIR/main.py >> $DIR/micropython/ports/esp32/modules/_boot.py`).
* It also works the same if I also uncomment the next line (`echo "\nCONFIG_BOOTLOADER_SKIP_VALIDATE_IN_DEEP_SLEEP=y" >> $DIR/micropython/ports/esp32/boards/sdkconfig.base`)

But if I also uncomment the third line (patching `ports/esp32/main.c`), the message gets sent exactly once when I reboot the board. I suspect that in the first run, the modification to `ports/esp32/main.c` has no effect (because `esp_reset_reason() == ESP_RST_DEEPSLEEP` is false), but that something goes wrong after that.

If there something obvious that I'm missing here?

**Update:** Oh, is it because `nvs_flash_init()` is required for wireless operation? I feel silly.

**Comment by glenn20** [comment]
Yes, that's right (I got caught with that too). I am thinking of submitting a PR that loads nvs_flash_init() only when it is required, rather than unconditionally at boot. However, I am not sure yet what other peripherals or components might be affected (besides wifi).
