### ISSUE TITLE
Commit 450b5a3 to skip SPIRAM initialization is no longer applicable?

### ISSUE THREAD

**Issue by mdaeron** [glenn20/upy-esp32-experiments#3]
Unless I'm missing something, commit [450b5a3](https://github.com/glenn20/micropython/commit/450b5a308df2e17eb2b740a49f65bb080c665612) can no longer be used on the latest version of micropython, because `ports/esp32/main.c` no longer has the line to be modified (`if (mp_task_heap == NULL) {`). I couldn't find how to do the same thing in the current code.

**Comment by glenn20** [comment]
Thanks for reporting this. Yes, there have been a lot of changes to how micropython handles both the heap and PSRAM on esp32 recently.

According to https://github.com/orgs/micropython/discussions/12316, this commit should no longer be necessary as the heap will grow according to demand, which means the initial gc_init() should complete very quickly, even if you have PSRAM. However, I have not tested that.

**Comment by glenn20** [comment]
I've added a note to this effect into the README.md.
